#! /bin/bash
# vim: fileencoding=utf8 foldmethod=marker
#{{{ License header: MIT
# Copyright (c) 2014 Till Maas <opensource@till.name>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#}}}

# Abort on failure
set -e

# For debugging
set -x

DESTDIR="${1:-${HOME}}"
TILLCONF="$(readlink -f "${0}")"

c() {
    cp "${TILLCONF}/${1}" "${DESTDIR}/${2:-${1}}"
}


cr() {
    cp -a "${TILLCONF}/${1}" "${DESTDIR}/${2:-${1}}"
}


md() {
    mkdir -p "${DESTDIR}/${1}"
}


lns() {
    ln -s -- "${TILLCONF}${1}" "${DESTDIR}/${2:-${1}}"
}

if [ ! -d ${DESTDIR}/.vim/bundle/neobundle ]
then
    echo "Installing neobundle..."
    git clone https://github.com/Shougo/neobundle.vim ${DESTDIR}/.vim/bundle/neobundle
    echo "done"
fi

lns .vimrc
