#! /bin/bash
# vim: fileencoding=utf8 foldmethod=marker
#{{{ License header: MIT
# Copyright (c) 2014 Till Maas <opensource@till.name>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#}}}

# Check whether script executed or sourced
if [ "$_" == "$0" ]
then
    # Script was executed
    TILLCONF_MAIN="true"
    DESTDIR="$(readlink -f ${1:-${HOME}})"
    TILLCONF="$(readlink -f "${0%/*}")/"
fi


# Abort on failure
set -e

# For debugging
set -x

# Generic utilities
commonprefix() {
    # Return common prefix of $1 and $2
    _IFS=$IFS
    IFS=/
    parts1=($1)
    parts2=($2)
    IFS=$_IFS

    # Initial
    prefix=""

    matching=1
    for ((i=0; i < ${#parts2[@]}; i++))
    do
        if [[ $matching && ${parts1[i]} == ${parts2[i]} ]]
        then
            #echo component ${parts2[i]} > /dev/stderr
            prefix+=${parts2[i]}/
            continue
        else
            #echo different component ${parts1[i]} ${parts2[i]} > /dev/stderr
            matching=0
        fi
    done
    # remove suffix
    if [[ "${prefix}" != "/" ]]
    then
        prefix=${prefix%/}
    fi
    echo "${prefix}"
}


relpath() {
    # Return relative path from $2 to $1
    dir1="${1%/*}"
    dir2="${2%/*}"
    prefix=$(commonprefix "${dir1}" "${dir2}")

    subdirs1=${dir1#${prefix}}
    subdirs2=${dir2#${prefix}}

    _IFS=$IFS
    IFS=/
    parts2=($subdirs2)
    IFS=$_IFS

    relativepath=""
    for ((i=0; i < ${#parts2[@]} - 1; i++))
    do
        relativepath+="../"
    done
    # remove trailing slash
    relativepath="${relativepath%/}"

    # add subdirs1
    relativepath+="${subdirs1%/}"

    # add last component of 1
    relativepath+="/${1##*/}"

    echo "${relativepath}"
}


relsymlink() {
    # Symlink to $1 from $2
    ln -s -- $(relpath "${@}") ${2}
}

# Used for config management
c() {
    cp "${TILLCONF}/${1}" "${DESTDIR}/${2:-${1}}"
}


cr() {
    cp -a "${TILLCONF}/${1}" "${DESTDIR}/${2:-${1}}"
}


md() {
    mkdir -p "${DESTDIR}/${1}"
}


lns() {
    relsymlink "${TILLCONF}${1}" "${DESTDIR}/${2:-${1}}"
}


main() {
    read -p "Going to install tillconf..."
    if [ ! -d ${DESTDIR}/.vim/bundle/neobundle ]
    then
        echo "Installing neobundle..."
        git clone https://github.com/Shougo/neobundle.vim ${DESTDIR}/.vim/bundle/neobundle
        echo "done"
    fi

    lns .vimrc
}


if [ -n "${TILLCONF_MAIN}" ]
then
    main
fi
